// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import { siteConfig } from "@/site.config";
import "./globals.css";

/*
  next/font/google requires font names to be statically analyzable, so the
  two fonts currently supported by this template are Poppins (heading) and
  Inter (body). Change here if siteConfig.theme.fonts changes.
*/
const heading = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--brand-font-heading",
  display: "swap",
});

const body = Inter({
  subsets: ["latin"],
  variable: "--brand-font-body",
  display: "swap",
});

const { business, seo, contact, theme } = siteConfig;

export const metadata: Metadata = {
  title: {
    default: seo.defaultTitle,
    template: `%s | ${business.name}`,
  },
  description: seo.defaultDescription,
  keywords: seo.keywords,
  icons: { icon: business.logo.favicon },
  openGraph: {
    type: "website",
    title: seo.defaultTitle,
    description: seo.defaultDescription,
    siteName: business.name,
    locale: "en_NG",
    ...(seo.ogImage ? { images: [{ url: seo.ogImage }] } : {}),
  },
  twitter: {
    card: seo.ogImage ? "summary_large_image" : "summary",
    title: seo.defaultTitle,
    description: seo.defaultDescription,
    ...(seo.ogImage ? { images: [seo.ogImage] } : {}),
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: business.name,
  description: business.description,
  url: "/",
  telephone: contact.phone,
  email: contact.email,
  address: {
    "@type": "PostalAddress",
    streetAddress: contact.address.street,
    addressLocality: contact.address.city,
    addressRegion: contact.address.state,
    addressCountry: contact.address.country,
  },
  openingHoursSpecification: contact.hours.map((h) => ({
    "@type": "OpeningHoursSpecification",
    dayOfWeek: h.day,
    opens: h.open,
    closes: h.close,
  })),
};

const rootStyle = `:root{--brand-primary:${theme.colors.primary};--brand-secondary:${theme.colors.secondary};--brand-background:${theme.colors.background};--brand-foreground:${theme.colors.foreground};--brand-muted:${theme.colors.muted};}`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${heading.variable} ${body.variable}`}>
      <head>
        <style dangerouslySetInnerHTML={{ __html: rootStyle }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="bg-background text-foreground antialiased">{children}</body>
    </html>
  );
}
